language: python
cache:
  timeout: 1800
  pip: true

# https://docs.travis-ci.com/user/languages/python/

jobs:
  include:
    - name: "Python 3.6 on Ubuntu"
      os: linux
      python: 3.6
    - name: "Python 3.7 on macOS 10.14"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - brew install ffmpeg
        - brew install cairo
        - pip3 install pycairo --user
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
         - choco install python --version 3.7.4

install:
  - pip3 install --upgrade pip || python -m pip install --upgrade pip --user
  - pip3 install wheel || pip3 install wheel --user
  - pip3 install -r requirements.txt || pip3 install -r requirements.txt --user
  - pip3 install -r tests/requirements.txt || pip3 install -r tests/requirements.txt --user
  - python3 setup.py install || python setup.py install

script:
  - python3 tests/ipytest.py --cov=data_vault -v || python tests/ipytest.py --cov=data_vault -v

after_success:
  - codecov
